
version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    image: todo:development
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
       - pg-dev-data:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      
volumes:
  pg-dev-data:
